name = "gptlauncher"
main = "server.js"
compatibility_date = "2024-01-01"
account_id = "47d96e6d04207519d2d6e98720aa49bd"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1
